services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - ./docker-data/keycloak-db:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0
    ports:
      - '8000:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    depends_on:
      - keycloak-db
    volumes:
      - ./docker-data/keycloak:/opt/jboss/keycloak/standalone/data
    command:
      - start-dev
